In [11]:
import pandas as pd

total_data2024 = pd.read_excel("../data/raw/all_alpha_24.xlsx")
total_data2023 = pd.read_excel("../data/raw/all_alpha_23.xlsx")
total_data2022 = pd.read_excel("../data/raw/all_alpha_22.xlsx")
total_data2021 = pd.read_excel("../data/raw/all_alpha_21.xlsx")
total_data2020 = pd.read_excel("../data/raw/all_alpha_20.xlsx")

total_data1.head()

,Model,Displ,Cyl,Trans,Drive,Fuel,Cert Region,Stnd,Stnd Description,Underhood ID,Veh Class,Air Pollution Score,City MPG,Hwy MPG,Cmb MPG,Greenhouse Gas Score,SmartWay
0,AUDI Q4 40 e-tron,NaN,NaN,Auto-1,2WD,Electricity,FA,T3B0,Federal Tier 3 Bin 0,RVGAV00.0NZ4,standard SUV,10,30,36,33,10,Elite
1,AUDI Q4 40 e-tron,NaN,NaN,Auto-1,2WD,Electricity,CA,ZEV,California ZEV,RVGAV00.0NZ4,standard SUV,10,30,36,33,10,Elite
2,AUDI Q4 50 e-tron quattro,NaN,NaN,Auto-1,4WD,Electricity,FA,T3B0,Federal Tier 3 Bin 0,RVGAJ00.0NZ5,standard SUV,10,97,87,93,10,Elite
3,AUDI Q4 50 e-tron quattro,NaN,NaN,Auto-1,4WD,Electricity,CA,ZEV,California ZEV,RVGAJ00.0NZ5,standard SUV,10,97,87,93,10,Elite
4,AUDI Q4 Sportback 50 e-tron quattro,NaN,NaN,Auto-1,4WD,Electricity,FA,T3B0,Federal Tier 3 Bin 0,RVGAJ00.0NZ5,standard SUV,10,100,89,95,10,Elite

In [12]:
total_data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 553 entries, 0 to 552
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Model                 553 non-null    object
 1   Displ                 100 non-null    float64
 2   Cyl                   100 non-null    float64
 3   Trans                 553 non-null    object
 4   Drive                 553 non-null    object
 5   Fuel                  553 non-null    object
 6   Cert Region           553 non-null    object
 7   Stnd                  553 non-null    object
 8   Stnd Description      553 non-null    object
 9   Underhood ID          553 non-null    object
 10  Veh Class             553 non-null    object
 11  Air Pollution Score   553 non-null    int64
 12  City MPG              553 non-null    object
 13  Hwy MPG               553 non-null    object
 14  Cmb MPG               553 non-null    object
 15  Greenhouse Gas Score  553 non-null    int64
 16  SmartWay              553 non-null    object
dtypes: float64(2), int64(2), object(13)
memory usage: 73.6+ KB

In [13]:
total_data1.shape

(553, 17)